export const LOADING_DIVES_LIST = 'LOADING_DIVES_LIST';
export const ADDING_DIVES_LIST = 'ADDING_DIVES_LIST';

export const UPDATING_DIVE = 'UPDATING_DIVE'
export const DIVE_PATCH_SUCCESSFUL = 'DIVE_PATCH_SUCCESSFUL'
export const DIVE_PATCH_FAILED = 'DIVE_PATCH_FAILED'

export const CREATING_DIVE = 'CREATING_DIVE'
export const CREATE_DIVE_SUCCESSFUL = 'CREATE_DIVE_SUCCESSFUL'
export const CREATE_DIVE_FAILED = 'CREATE_DIVE_FAILED'

export const DELETE_DIVE = 'DELETE_DIVE'
export const DELETE_DIVE_SUCCESSFUL = 'DELETE_DIVE_SUCCESSFUL'
export const DELETE_DIVE_FAILED = 'DELETE_DIVE_FAILED'