export const LOADING_DIVES_LIST = 'LOADING_DIVES_LIST';
export const ADDING_DIVES_LIST = 'ADDING_DIVES_LIST';
export const UPDATING_DIVE = 'UPDATING_DIVE'
export const DIVE_PATCH_SUCCESSFUL = 'DIVE_PATCH_SUCCESSFUL'