export const LOADING_LOCATIONS = 'LOADING_LOCATIONS';
export const UPDATING_LOCATIONS = 'UPDATING_LOCATIONS';

export const UPDATING_LOCATION = 'UPDATING_LOCATION';
export const LOCATION_PATCH_SUCCESSFUL = 'LOCATION_PATCH_SUCCESSFUL';
export const LOCATION_PATCH_FAILED = 'LOCATION_PATCH_FAILED';

export const CREATING_LOCATION = 'CREATING_LOCATION';
export const CREATE_LOCATION_SUCCESSFUL = 'CREATE_LOCATION_SUCCESSFUL';
export const CREATE_LOCATION_FAILED = 'CREATE_LOCATION_FAILED';

export const DELETE_LOCATION = 'DELETE_LOCATION';
export const DELETE_LOCATION_SUCCESSFUL = 'DELETE_LOCATION_SUCCESSFUL';
export const DELETE_LOCATION_FAILED = 'DELETE_LOCATION_FAILED';

export const RESET_ERRORS = 'RESET_ERRORS';